<?php

return
[
    201101101 => [
        1 => [
            'gacha_id'         => 201101101,
            'step_count'       => 1,
            'price'            => 25,
            'draw_count'       => 1,
            'lottery_id'       => 101101101,
            'fixed_draw_count' => 0,
            'fixed_lottery_id' => null,
            'bonus_draw_count' => null,
            'bonus_lottery_id' => null,
            'total_play_limit' => 0,
            'daily_play_limit' => 0,
        ],
        2 => [
            'gacha_id'         => 201101101,
            'step_count'       => 2,
            'price'            => 75,
            'draw_count'       => 3,
            'lottery_id'       => 101101101,
            'fixed_draw_count' => 0,
            'fixed_lottery_id' => null,
            'bonus_draw_count' => null,
            'bonus_lottery_id' => null,
            'total_play_limit' => 0,
            'daily_play_limit' => 0,
        ],
        3 => [
            'gacha_id'         => 201101101,
            'step_count'       => 3,
            'price'            => 125,
            'draw_count'       => 5,
            'lottery_id'       => 101101101,
            'fixed_draw_count' => 0,
            'fixed_lottery_id' => null,
            'bonus_draw_count' => null,
            'bonus_lottery_id' => null,
            'total_play_limit' => 0,
            'daily_play_limit' => 0,
        ],
        4 => [
            'gacha_id'         => 201101101,
            'step_count'       => 4,
            'price'            => 175,
            'draw_count'       => 7,
            'lottery_id'       => 101101101,
            'fixed_draw_count' => 0,
            'fixed_lottery_id' => null,
            'bonus_draw_count' => null,
            'bonus_lottery_id' => null,
            'total_play_limit' => 0,
            'daily_play_limit' => 0,
        ],
        5 => [
            'gacha_id'         => 201101101,
            'step_count'       => 5,
            'price'            => 225,
            'draw_count'       => 9,
            'lottery_id'       => 101101101,
            'fixed_draw_count' => 1,
            'fixed_lottery_id' => 201101101,
            'bonus_draw_count' => null,
            'bonus_lottery_id' => null,
            'total_play_limit' => 0,
            'daily_play_limit' => 0,
        ],
    ],
];